site_name: Ben Hill's Wiki
site_url: https://github.com/ben-hill33/wikiheim

theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - attr_list
  - admonition
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True
  - search

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Python:
        - Data Types: 
            - Py Basics Buffet: 'python-fun/data-types/pre-work.md'
            - Lists: 'python-fun/data-types/list-methods.md'
            - List Processing: 'python-fun/data-types/lists.ipynb'
            - List Solutions: 'python-fun/data-types/list-solutions.md'
            - Dictionaries: 'python-fun/data-types/dict.md'
            - Vectors: 'python-fun/data-types/vectors.md'
            - Classes and Objects: 'python-fun/data-types/classes-objects.md'
        - Error Handling:
            - Bugs, Debugging, and Exceptions: 'python-fun/error-handling/err-hand.md'
        - Data Structures:
            - Py Data Structure Buffet: 'python-fun/data-structures/pre-work-advanced.md'
        - Modules:
            - Regex: 'python-fun/notebooks/re-patterns.ipynb'
        - Data Science:
            - Data Analysis: 'python-fun/data-science/data-analysis.md'
            - Linear Regression: 'python-fun/data-science/linear-regressions.md'
            - Webscraping: 'python-fun/data-science/webscrape.md'
        - Django:
            - Intro to Django: 'python-fun/django/django.md'
            - Data Models: 'python-fun/django/django-models.md'
            - Django Forms: 'python-fun/django/django-crud-forms.md'
            - Django Custom User: 'python-fun/django/django-custom-user.md'
            - Django REST Framework & Docker: 'python-fun/django/dj-rest-docker.md'
        - File System:
            - FileIO & Exceptions: 'python-fun/FS-IO/file-and-exceptions.md'
        - Full Stack:
            - React, Tailwind CSS, and Next.js: 'python-fun/py-react/py-react.md'
        - Security:
            - Cryptography: 'python-fun/py-sec/cryptography.md'
            - API Access Management: 'python-fun/py-sec/api-integration.md'
        - Testing:
            - Pytest: 'python-fun/testing/python-tdd.md'
    - Programming:
        - Database:
            - The Story of Data: 'programming/database/data-story.md'
            - SQL: 'programming/database/sql.md'
            - Normalization: 'programming/database/db-normalize.md'
            - Backend Performance: 'programming/database/backend-performance.md'
            - Data in Microservices: 'programming/database/data-in-micro.md'
        - Intro to Operating Systems:
            - Networks: 'programming/operating-systems/networking.md'
            - Security, Troubleshooting, and Performance: 'programming/operating-systems/sec.md'
            - SSH: 'programming/operating-systems/intro-to-ssh.md'
    - Data Structures & Algorithms:
        - Breadth First Search: 'dsa/algorithms/breadth-first.md'
        - Complexity: 'dsa/complexity/O(n).md'
        - Big O: 'dsa/complexity/beginner-big-O.md'
        - Good Code: 'dsa/complexity/good-code.md'
        - Space: 'dsa/complexity/spacing.md'
        - Time: 'dsa/complexity/timing-code.md'
        - Linked List: 'dsa/data-structures/link-list.md'
        - Hash Tables: 'dsa/data-structures/hash-tables.md'
        - Stacks & Queues: 'dsa/data-structures/stack-que.md'
        - Trees: 'dsa/data-structures/trees.md'
        - Graphs: 'dsa/data-structures/graphs.md'
    - Website Hub:
        - Basic:
            - Intro to HTML and JS: 'web-dev/201/201-class-01.md'
            - HTML Text, CSS Intro, Basic JS Instructions: 'web-dev/201/201-class-02.md'
            - HTML Lists, CSS Boxes, JS Control Flow: 'web-dev/201/201-class-03.md'
            - HTML Links, CSS Layouts, JS Functions: 'web-dev/201/201-class-04.md'
            - HTML Images; CSS Color & Text: 'web-dev/201/201-class-05.md'
            - HTML Canvas Element & Charts: 'web-dev/201/201-class-12.md'
            - HTML Tables, JS Constructor Functions: 'web-dev/201/201-class-07.md'
            - More CSS Layout: 'web-dev/201/201-class-08.md'
            - CSS Transforms, Transitions, and Animations: 'web-dev/201/css-trans-ani.md'
            - JS Object Literals, The DOM: 'web-dev/201/201-class-06.md'
            - Forms and Events: 'web-dev/201/201-class-09.md'
            - JS Debugging: 'web-dev/201/201-class-10.md'
            - Local Storage: 'web-dev/201/201-class-13.md'
            - Assorted Topics: 'web-dev/201/201-class-11.md'
        - Intermediate:
              - 'web-dev/301/301-class-01.md'
              - 'web-dev/301/301-class-02.md'
              - 'web-dev/301/301-class-04.md'
              - 'web-dev/301/301-class-05.md'
              - 'web-dev/301/301-class-06.md'
              - 'web-dev/301/301-class-07.md'
              - 'web-dev/301/301-class-09.md'
              - 'web-dev/301/301-class-10.md'
              - 'web-dev/301/301-class-13.md'
        - Advanced:
              - 'web-dev/401-js/401-js-class-01-b.md'
              - 'web-dev/401-js/401-js-class-01.md'
              - 'web-dev/401-js/401-js-class-02.md'
              - 'web-dev/401-js/class-08.md'
              - 'web-dev/401-js/class-09.md'
              - 'web-dev/401-js/class-11.md'
              - 'web-dev/401-js/class-13.md'
              - 'web-dev/401-js/class-14.md'
              - 'web-dev/401-js/class-15.md'
              - 'web-dev/401-js/class-16.md'
              - 'web-dev/401-js/class-17.md'
              - 'web-dev/401-js/class-19.md'
              - 'web-dev/401-js/class-20.md'
              - 'web-dev/401-js/class-26.md'
              - 'web-dev/401-js/class-27.md'
              - 'web-dev/401-js/class-28.md'
              - 'web-dev/401-js/class-29-2.md'
              - 'web-dev/401-js/class-30.md'
              - 'web-dev/401-js/class-31.md'
              - 'web-dev/401-js/class-32.md'
              - 'web-dev/401-js/class-33.md'
              - 'web-dev/401-js/class-35.md'
              - 'web-dev/401-js/class-36.md'
              - 'web-dev/401-js/class-37.md'
              - 'web-dev/401-js/class-38.md'
              - 'web-dev/401-js/class-39.md'
              - 'web-dev/401-js/js-class-03.md'
              - 'web-dev/401-js/js-class-04.md'
              - 'web-dev/401-js/js-class-06.md'
              - 'web-dev/401-js/js-class-07.md'
              - 'web-dev/401-js/react-native.md'
              - 'web-dev/401-js/react.md'
              - 'web-dev/401-js/redux-additional.md'
              - 'web-dev/401-js/redux.md'
              - 'web-dev/401-js/typescript.md'

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js