site_name: BenHeim Wiki
site_url: https://github.com/ben-hill33/wikiheim

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - admonition

plugins:
  - mkdocs-jupyter

nav:
- Home: 'index.md'
- About: 'about.md'
- Python:
    - Data-Types: 
        - 'python/data-types/lists.ipynb'
        - 'python/data-types/dict.md'
        - 'Objects and Recursion': 'classes-objects.md'
- Intro to Operating Systems:
    - 'Networking': 'networking.md'
    - 'Security, Troubleshooting, and Performance': 'sec.md'



