site_name: BenHeim Wiki
site_url: https://github.com/ben-hill33/wikiheim

theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  

plugins:
  - mkdocs-jupyter
  - search

nav:
- Home: 'index.md'
- About: 'about.md'
- Python:
    - Data Types: 
        - 'python-fun/data-types/lists.ipynb'
        - 'python-fun/data-types/dict.md'
        - 'python-fun/data-types/classes-objects.md'
    - Data Science:
        - 'python-fun/data-science/data-analysis.md'
    - Django:
        - 'python-fun/django/django.md'
    - File System & IO:
        - 'python-fun/FS-IO/file-and-exceptions.md'
    - API's:
        - 'python-fun/py-api/api-integration.md'
    - Full Stack:
        - 'python-fun/py-react/py-react.md'
    - Security:
        - 'python-fun/py-sec/cryptography.md'
    - Testing:
        - 'python-fun/testing/pytest.md'
- Intro to Operating Systems:
    - Networks: 'operating-systems/networking.md'
    - Security, Troubleshooting, and Performance: 'operating-systems/sec.md'

extra_css:
  - stylesheets/extra.css

